#!/usr/bin/env node

/* eslint-disable */
const fs = require('fs');
const colors = require('colors/safe');
const { promisify } = require('util');
const camelCase = require('lodash/camelCase');
const kebabCase = require('lodash/kebabCase');
const identity = require('lodash/identity');
const readFile = promisify(fs.readFile);
const writeFile = promisify(fs.writeFile);

/*
    The BDL classname manager is a tool to help identify and correct the usage of classnames
    names across box-ui-elements, and other projects.

    HOW TO RUN:
    cd src/
    // .scss
    find . -name "*.scss" -exec ../scripts/utils/bdlClassnameManager swap {} \;
    // .js
    find . -not -name "*test.js" -and -name "*.js" -exec ../scripts/utils/bdlClassnameManager swap {} \;
    // -test.js
    find . -name "*test.js" -exec ../scripts/utils/bdlClassnameManager swap {} '' --tests \;
*/

/*
    TODO:
    * What to do with span?
    * should run *-test.js with '. prefix instead of ' prefix
    * Tooltip.js uniqueId
*/

const extendedConversionMap = {
    /* TOOLTIP */
    'tooltip-icon-container': 'bdl-Tooltip-iconContainer',
    'tooltip-close-button': 'bdl-Tooltip-closeButton',
    'tooltip-target-attached-top': 'bdl-Tooltip--targetAattachedTop',
    'tooltip-target-attached-center': 'bdl-Tooltip--targetAattachedCenter',
    'tooltip-target-attached-left': 'bdl-Tooltip--targetAattachedLeft',
    'tooltip-target-attached-right': 'bdl-Tooltip--targetAattachedRight',
    'tooltip-target-attached-middle': 'bdl-Tooltip--targetAattachedMiddle',
    'tooltip-target-attached-bottom': 'bdl-Tooltip--targetAattachedBottom',
    /* BUTTON */
    // 'btn-primary': 'bdl-Button--primary',
    // 'btn-plain': 'bdl-Button--plain',
    // 'btn-group': 'bdl-ButtonGroup',
    // 'select-button': 'bdl-SelectButton',
    // 'btn-done': 'bdl-Button--done',
    // 'btn-loading-indicator': 'bdl-Button-loadingIndicator',
    /* IS DISABLED */
    // 'is-disabled': 'bdl-is-disabled',
    /* LABEL */
    // 'label-optional': 'bdl-Label--optional',
    /* PILL */
    // 'pill-error': 'bdl-Pill--error',
    // 'pill-cloud-button': 'bdl-PillCloud-button',
    // 'pill-cloud-container': 'bdl-PillCloud-container',
    // 'pill-selector-error': 'bdl-PillSelector--error',
    // 'pill-selector-hidden-input': 'bdl-PillSelector-hiddenInput',
    // 'pill-selector-input': 'bdl-PillSelector-input',
    // 'pill-selector-input-wrapper': 'bdl-PillSelector-inputWrapper',
    // 'pill-selector-suggested': 'bdl-PillSelector-suggested',
    // 'pill-selector-suggestions-enabled': 'bdl-PillSelector--suggestionsEnabled',
    // 'pill-selector-wrapper': 'bdl-PillSelector-wrapper',
    // 'pill-warning': 'bdl-Pill--warning',
    // 'pills-list': 'bdl-Pills-list',
    /* TOGGLE */
    // 'toggle-overlay-container': 'bdl-Toggle-overlayContainer',
    // 'toggle-simple-switch': 'bdl-Toggle-simpleSwitch',
    // 'toggle-simple': 'bdl-Toggle-simple',
    // 'toggle-simple-input': 'bdl-Toggle-simpleInput',
    // 'toggle-simple-description': 'bdl-Toggle-simpleDescription',
};

const baseConversionMap = {
    /* TOOLTIP */
    'tooltip': 'bdl-Tooltip',
    /* OTHERS - uncomment as needed */
    // 'btn': 'bdl-Button',
    // 'label': 'bdl-Label',
    // 'pill': 'bdl-Pill',
    // 'toggle': 'bdl-Toggle',
};

function printHelp() {
    console.log(`Usage: ${process.argv[1].split('/').pop()} operation fileName [--verbose] [--tests]`);
    console.log('\nSupported operations:');
    console.log('\tcheck\t\tcheck to see if a file contains deprecated values (returns error if it does)');
    console.log('\tswap\t\treplace known-deprecated variable names in a JS or SCSS file');
}

async function processFile(conversionMap) {
    // argv 0 and 1 are the node instance and the script name respectively.
    // argv 2 is the operation: check, swap, ...
    const operation = process.argv[2];

    // argv 3 is the file (and extension)
    const fileName = process.argv[3];

    if (!fileName) {
        console.error(colors.red('Missing parameter:'), colors.white('fileName'));
        process.exit(1);
    }
    const fileType = fileName.split('.').pop();
    const verboseMode = process.argv[4] === '--verbose';
    const testMode = process.argv[5] === '--tests';

    let reBadName;
    if (fileType === 'scss' || (fileType === 'js' && testMode)) {
        // only make changes in .scss files for classnames prefixed with '.'
        const converter = entry => `\\.${entry}`;
        reBadName = new RegExp(Object.keys(conversionMap).map(converter).join('|'), 'g');
    } else if (fileType === 'js') {
        // only make changes in .js files for classnames prefixed with " or ' or `
        const doubleQuoteConverter = entry => `"${entry}`;
        const singleQuoteConverter = entry => `'${entry}`;
        const backtickConverter = entry => `\`${entry}`;
        reBadName = new RegExp(
            Object.keys(conversionMap).map(doubleQuoteConverter).join('|')
                .concat('|')
                .concat(Object.keys(conversionMap).map(singleQuoteConverter).join('|'))
                .concat('|')
                .concat(Object.keys(conversionMap).map(backtickConverter).join('|')),
            'g',
        );

    }

    try {
        const fileToParse = await readFile(fileName, { encoding: 'utf8' });

        switch (operation) {
            case 'check':
                // determine if the file is using one of the legacy variable names
                const foundMatch = reBadName.test(fileToParse);
                if (foundMatch) {
                    // Exit with an error code: we should not find bad names
                    if (verboseMode) {
                        console.error(colors.red('Bad BDL class name found in', fileName));
                    }
                    process.exit(1);
                }

                break;
            case 'swap':
                // find, then swap in the proper new name
                const matches = [...new Set(fileToParse.match(reBadName))];
                let replacementFile = fileToParse;

                if (verboseMode) {
                    console.log(colors.cyan('File name:'), colors.white(fileName));
                    console.log(colors.cyan('Found:'), matches);
                }

                matches.forEach(match => {
                    if (fileType === 'scss' || (fileType === 'js' && testMode)) {
                        replacementFile = replacementFile.replace(new RegExp(`\\${match}`, 'g'), `.${conversionMap[kebabCase(match)]}`);
                    } else if (fileType === 'js') {
                        const quotationType = /"/.test(match)
                            ? '"'
                            : /'/.test(match)
                                ? '\''
                                : '`';
                        replacementFile = replacementFile.replace(new RegExp(match, 'g'), `${quotationType}${conversionMap[kebabCase(match)]}`);
                    } else {
                        console.error(colors.yellow('Unrecognized file type for conversion. skipping', fileName, '...'));
                        process.exit(0);
                    }
                });

                try {
                    if (matches.length > 0) {
                        await writeFile(fileName, replacementFile);
                        console.log (colors.cyan(`Replaced ${matches.length} classname value${matches.length !== 1 ? 's': ''} in:\t`), fileName);
                    } else if (verboseMode) {
                        console.warn(colors.yellow('No changes needed to file:\t'), fileName);
                    }
                } catch (error) {
                    console.error(colors.red('Cannot write updated file to disk\n'), error);
                    process.exit(1);
                }

                break;
            default:
                console.error(colors.red('Unrecognized operation:'), colors.white(operation));
                console.error(colors.red('use "swap" to replace names, or "check" to verify if a file contains deprecated values'));
                process.exit(1);
                break;
        }
    } catch (error) {
        console.error(colors.red('Cannot read file, because it does not exist or the wrong path is specified\n'), error);
        process.exit(1);
    }
}

async function main() {
    // process conversion maps separately, so the basic classnames don't override the longer classnames:
    await processFile(extendedConversionMap);
    processFile(baseConversionMap);
}

if (process.argv.length < 3) {
    printHelp();
} else {
    main();
}
